name: pixiv_func_i18n_expansion
description: Pixiv Func I18n Generator

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

